### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by Tim020** [Tim020/SUPER-SEPR#41]
Refactor the test framework provided by BugFree to use Unity Test Tools so we can get CI testing and reports. Current tests are found under the Classes/Tests folder, UTT tests should be under Editor/Tests folder. See the master branch under Game/Assets/Editor/Tests to see how UTT tests are structured.

**Comment by Tim020** [comment]
@MIDunn @jcf518 How many tests have you got left to port?

**Comment by MIDunn** [comment]
@Tim020  Just waiting on ResourceGroup (5) tests and Roboticons (which I'm doing now and they only had 4). We're unable to test the scoring mechanism as that's going to be changed, we also aren't able to test the game handler and manager because you guys are changing it atm.

**Comment by jcf518** [comment]
@MIDunn @Tim020 Just working on the ResourceGroup tests now

**Comment by jcf518** [comment]
@MIDunn Hi i'm having trouble finding the ResourceGroup class to work on though it might just be my laptop. If it is I'll come into uni to work on it there.

**Comment by MIDunn** [comment]
@jcf518 sorry about the late reply only just checked my email. As for the ResourceGroup class it should be under Game/Assets/Classes/ResourceGroup.cs, as for the testing class that should go in Game/Assets/Editor/Tests
