### ISSUE TITLE
Implement AI Player

### ISSUE THREAD

**Issue by theobarberbany** [Tim020/SUPER-SEPR#44]
- [x] Implement AI Actions

- [x] Intelligent Decision of best upgrade

- [x] Decide if roboticon purchase is justified

- [x] Get optimal tile for roboticon

- [x] Optimal tile acquisition

**Comment by MIDunn** [comment]
@Tim020 hey could you take a quick look at the AI branch. I'm sure mostly everything is implemented  (bar player to AI trading) but I'm having some problems testing it, it seems there's an issue with the roboticon customisation phase for the AI as it seems it doesn't actually get called. It just waits for 1 minute before proceeding to roboticon placement, although on debuging it seems the game manager enters the phase just for some reason it doesn't appear to be calling the start phase method.

**Comment by Tim020** [comment]
Created an issue #70 to keep track of this
