### ISSUE TITLE
Win condition

### ISSUE THREAD

**Issue by MIDunn** [Tim020/SUPER-SEPR#57]
The player's score needs to be calculated based on resources owned as well as roboticons worth.
Score could be calculated each turn, or just once at the end of the game.

- [x] Game ends when there are no tiles left to purchase

- [x] Score is calculated, and the winner displayed

- [x] Player Score = Money + (Ore * MarketOrePrice) + (Food * MarketFoodPrice) + (Energy * MarketEnergyPrice) + Sum of all Roboticon.GetPrice()
NOTE: This market price should be the same for both players.

**Comment by Tim020** [comment]
How is this going?

**Comment by jcf518** [comment]
Working on it but I've been concentrating on ARIN. I'll get it done after tomorrow's exam.

**Comment by jcf518** [comment]
I've changed this so we calculate the player score with the resource amounts rather than multiplying them by their selling prices which proved difficult and isn't necessary to determine the winner. Was it a requirement to use selling prices to calculate the score?

**Comment by Tim020** [comment]
I will have a look and finish this off this morning (easier for me to add the UI stuff as it's gonna be a pain in the ass to merge together later). :)
